wandb_version: 1

input_bin:
  desc: null
  value: data/fineweb10B/fineweb_train_*.bin
input_val_bin:
  desc: null
  value: data/fineweb10B/fineweb_val_*.bin
batch_size:
  desc: null
  value: 512
device_batch_size:
  desc: null
  value: 32
sequence_length:
  desc: null
  value: 1024
num_iterations:
  desc: null
  value: 5001
learning_rate:
  desc: null
  value: 0.00036
warmup_iters:
  desc: null
  value: 0
warmdown_iters:
  desc: null
  value: 0
weight_decay:
  desc: null
  value: 0
val_loss_every:
  desc: null
  value: 50
val_tokens:
  desc: null
  value: 10485760
save_every:
  desc: null
  value: 0
n_layer:
  desc: null
  value: 12
n_head:
  desc: null
  value: 6
n_embd:
  desc: null
  value: 768
unconstrained:
  desc: null
  value: true
momentum:
  desc: null
  value: 0.1
scale:
  desc: null
  value: 50
last_scale:
  desc: null
  value: 3000
_wandb:
  desc: null
  value:
    python_version: 3.12.4
    cli_version: 0.17.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1743185168
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.12.4
      5: 0.17.9
      8:
      - 5
      13: linux-x86_64
